// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: poc2-proto.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace POC2 {
  public static partial class CameraPositionService
  {
    static readonly string __ServiceName = "POC2.CameraPositionService";

    static readonly grpc::Marshaller<global::POC2.PositionRequest> __Marshaller_POC2_PositionRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::POC2.PositionRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::POC2.PositionReply> __Marshaller_POC2_PositionReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::POC2.PositionReply.Parser.ParseFrom);

    static readonly grpc::Method<global::POC2.PositionRequest, global::POC2.PositionReply> __Method_GetCameraPosition = new grpc::Method<global::POC2.PositionRequest, global::POC2.PositionReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetCameraPosition",
        __Marshaller_POC2_PositionRequest,
        __Marshaller_POC2_PositionReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::POC2.Poc2ProtoReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of CameraPositionService</summary>
    [grpc::BindServiceMethod(typeof(CameraPositionService), "BindService")]
    public abstract partial class CameraPositionServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::POC2.PositionReply> GetCameraPosition(global::POC2.PositionRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for CameraPositionService</summary>
    public partial class CameraPositionServiceClient : grpc::ClientBase<CameraPositionServiceClient>
    {
      /// <summary>Creates a new client for CameraPositionService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public CameraPositionServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for CameraPositionService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public CameraPositionServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected CameraPositionServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected CameraPositionServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::POC2.PositionReply GetCameraPosition(global::POC2.PositionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCameraPosition(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::POC2.PositionReply GetCameraPosition(global::POC2.PositionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetCameraPosition, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::POC2.PositionReply> GetCameraPositionAsync(global::POC2.PositionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCameraPositionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::POC2.PositionReply> GetCameraPositionAsync(global::POC2.PositionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetCameraPosition, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override CameraPositionServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new CameraPositionServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(CameraPositionServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetCameraPosition, serviceImpl.GetCameraPosition).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, CameraPositionServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetCameraPosition, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::POC2.PositionRequest, global::POC2.PositionReply>(serviceImpl.GetCameraPosition));
    }

  }
}
#endregion
